version: "3"
services:
  backend:
    container_name: moyobar_backend
    image: "moyobar_backend:0.1"
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - moyobar
    environment:
      - TZ=Asia/Seoul
  nginx:
    restart: always
    container_name: "moyobar_frontend"
    image: "moyobar_frontend:0.1"
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - moyobar
    environment:
      - TZ=Asia/Seoul

networks:
  moyobar:
