version: "3.1"
services:
  jenkins:
    restart: always
    container_name: jenkins
    build:
      dockerfile: Dockerfile
      context: ./
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Asia/Seoul"
