#it will be set build date by gradle. if this value is @build.date@, front-end is development mode
build:
  date: @build.date@

server:
  port: 8080
  address: localhost
  servlet:
    contextPath: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression: #gzip compression
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  profiles:
    include: secret
  devtools:
    livereload:
      enabled: true
  resources: #for SPA
    #static-locations: #classpath:/dist/
    add-mappings: false
  mvc: # for SPA
    throw-exception-if-no-handler-found: true
  jpa: #database
    show-sql: true #show hibernate sql
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: update #db auto update
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true #pretty formatting
  data: #database
    web:
      pageable:
        one-indexed-parameters: true

spa:
  default-file: /dist/index.html

# Swagger
springfox:
  documentation:
    swagger:
      use-model-v3: false

#logging
logging:
  file:
    name: ./ssafy-web.log
  level:
    root: INFO
  com:
    samsung:
      security: DEBUG
  org:
    springframework:
      web: DEBUG
    apache:
      tiles: INFO
    sringframework:
      boot: DEBUG
      security: DEBUG

#for health check
management:
  servlet:
    context-path: /manage
  health:
    db:
      enabled: true
    default:
      enabled: true
    diskspace:
      enabled: true